version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    cpuset: "0"
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  
  app: 
    image: yanovitchsky/pfeo:v3
    depends_on:
      - mongo
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - pfeo_game:/app
    # env_file: .env.production
    tty: true
    environment:
      RAILS_ENV: production
      MONGO_URL: mongodb://mongo:27017/pfeo_production
      REDIS_URL: redis://redis:6379/1
      PORT: 3000
      RAILS_SERVE_STATIC_FILES: 'true'
      SECRET_KEY_BASE: de9737764f76e3a0bdbbb55a8ee75e367373d920a648fc8d95061fda3ea34839040ead154845d6cd2af9f9a33a915ccdfdd5de752ed470aad9853f984264ad7d

volumes:
  mongo_data:
  redis:
  pfeo_game: